-- =========================================================
-- 08a_cleanup_DRY_RUN.sql     bobcat-dev test-data cleanup     *** DRY RUN: ends in ROLLBACK, changes nothing ***
-- Generated by tools/generate_cleanup_sql.mjs from the approved inventories (scripts 06 + 07) and the owner-approved classification:
--   DELETE 216 + HOLD 17 (all approved for deletion) = 233 items, KEEP 3 (owner auth user, owner profile, task-attachments bucket + its policies).
-- Of the 233: 225 rows are deleted by THIS script (26 tables); 8 are removed in the Dashboard afterwards (3 test auth users,
-- their 3 profiles by cascade, 2 storage files) - see 09_DASHBOARD_STEPS.md. profiles / auth.users / storage.objects / the bucket are NOT touched here.
--
-- RUN IT ON: bobcat-dev ONLY, in the SQL Editor (role postgres). NEVER on the old legacy project (guard 1 refuses if legacy tables exist).
-- ORDER OF OPERATIONS: 1) run 08a (dry run)  2) run 08b (execute)  3) Dashboard steps  4) run 10_post_dashboard_verify_readonly.sql
-- Everything below is ONE transaction: if any guard, precondition, delete or post-check fails, NOTHING is deleted.
-- (The SQL Editor may ask you to confirm because the script contains DELETE statements - that is expected.)
-- Does not touch the old project, workspace_state, the schema, policies, functions, triggers, grants or the Auth configuration.
-- =========================================================
begin;
set local row_security = off;
set local lock_timeout = '15s';

-- ---------------------------------------------------------
-- 1) GUARD: this must be bobcat-dev, not the legacy project. The legacy project has workspace_state / orders / subteams.
-- ---------------------------------------------------------
do $guard$
begin
  if to_regclass('public.workspace_state') is not null or to_regclass('public.orders') is not null or to_regclass('public.subteams') is not null then
    raise exception 'ABORT (guard): legacy tables exist - this looks like the OLD live project. Nothing was changed.';
  end if;
  if to_regclass('public.profiles') is null or to_regclass('public.tasks') is null or to_regclass('public.migration_exceptions') is null then
    raise exception 'ABORT (guard): the v2 tables are missing - this is not bobcat-dev. Nothing was changed.';
  end if;
  if not exists (select 1 from auth.users where id = 'f15d8647-6a00-493a-8c07-1070f9a66b9b'::uuid) then
    raise exception 'ABORT (guard): the owner account f15d8647-6a00-493a-8c07-1070f9a66b9b is not in auth.users. Nothing was changed.';
  end if;
end
$guard$;

-- ---------------------------------------------------------
-- 2) LOCK the 26 data tables against writes (reads still work) so nothing can change between the check and the deletes
-- ---------------------------------------------------------
lock table public.audit_logs, public.cad_review_comments, public.cad_review_versions, public.cad_reviews, public.calendar_events, public.comment_mentions, public.member_applications, public.migration_exceptions, public.notifications, public.purchase_request_items, public.purchase_status_history, public.purchase_requests, public.subsystem_members, public.task_assignees, public.task_attachments, public.task_comments, public.task_requests, public.tasks, public.timeline_milestones, public.milestones, public.recurring_events, public.subsystem_categories, public.subsystems, public.timeline_columns, public.competition_settings, public.migration_log in exclusive mode;

-- ---------------------------------------------------------
-- 3) PRECONDITION: the database must match the approved inventory EXACTLY - row count AND an md5 fingerprint of the sorted row keys - for the
--    26 tables to be emptied and for the objects that must stay unchanged (profiles, auth.users, storage.objects).
--    A single extra, missing or different row aborts the whole run before anything is deleted.
-- ---------------------------------------------------------
create temp table _cleanup_expected (sch text, tbl text, key_expr text, n bigint, h text) on commit drop;
insert into _cleanup_expected values
  ('public', 'audit_logs', 'id::text', 0, 'd41d8cd98f00b204e9800998ecf8427e'),
  ('public', 'cad_review_comments', 'id::text', 6, '29ad6093a00c51ec09fd9cc9f07394ba'),
  ('public', 'cad_review_versions', 'id::text', 13, '36181915c6125917d555adce2462330b'),
  ('public', 'cad_reviews', 'id::text', 18, '6f3783d3005b7ab9b1015b8a0d92ca1a'),
  ('public', 'calendar_events', 'id::text', 3, '8efa45c8753edc40c97c2936966c06fe'),
  ('public', 'comment_mentions', 'comment_id::text || ''/'' || mentioned_profile_id::text', 12, 'bf8ed9b5ab59abf3c780ed4cfe88ed46'),
  ('public', 'competition_settings', 'season', 5, '9b397acb5978c3ce1165618cbe01e5ac'),
  ('public', 'member_applications', 'id::text', 6, '82faa9577e97d690a4523f47a7078f27'),
  ('public', 'migration_exceptions', 'id::text', 3, '1e0d8ea0b4738daa8e3e5d23f1cbd0d9'),
  ('public', 'migration_log', 'id::text', 0, 'd41d8cd98f00b204e9800998ecf8427e'),
  ('public', 'milestones', 'id::text', 2, 'bf75111a40516bbf9559c615b93c28a8'),
  ('public', 'notifications', 'id::text', 19, '96b1c92a9de0aa4deb72d8e578262f49'),
  ('public', 'purchase_request_items', 'id::text', 2, 'c891f632d64e13410dccd553e00c86c3'),
  ('public', 'purchase_requests', 'id::text', 11, '2a2383e275d88627f96a048389ae0b5a'),
  ('public', 'purchase_status_history', 'id::text', 35, 'e58c3c2d9f287f5d994d8eb3088b283d'),
  ('public', 'recurring_events', 'id::text', 2, '41eb681f6cf8969c316b75b9befac8c0'),
  ('public', 'subsystem_categories', 'id::text', 11, 'd9639ca2c950482901b5d41eab756578'),
  ('public', 'subsystem_members', 'subsystem_id || ''/'' || user_id::text', 4, 'c880b0f449fc4af81ff3f81444ab2ef1'),
  ('public', 'subsystems', 'id', 3, '0c493accc022549ea885c7d86302390c'),
  ('public', 'task_assignees', 'task_id::text || ''/'' || user_id::text', 5, '5fcb1ccef0c2a0289cabb6d820cff1bb'),
  ('public', 'task_attachments', 'id::text', 7, '0ef4b29bd785365848a96f26f994be6d'),
  ('public', 'task_comments', 'id::text', 14, '090f35db5e75584c8c435cb717ee6dec'),
  ('public', 'task_requests', 'id::text', 13, 'eb9b3bba5d8f7d34e98f10383a5e017a'),
  ('public', 'tasks', 'id::text', 23, '5a3d718de8b734e044cdaf53098386a1'),
  ('public', 'timeline_columns', 'key', 6, 'e761c12da9f77ae4d323905a821d7637'),
  ('public', 'timeline_milestones', 'subsystem_id || ''/'' || timeline_column_key', 2, 'ba6a921a705886f321c50a88c125798a'),
  ('public', 'profiles', 'id::text', 4, '33fa4fb9c385cab3f26976f398813540'),
  ('auth', 'users', 'id::text', 4, '33fa4fb9c385cab3f26976f398813540'),
  ('storage', 'objects', 'bucket_id || ''/'' || name', 2, 'b75b8b59e4d802031f36da16d0a82a85');

do $pre$
declare
  r record;
  actual_n bigint;
  actual_h text;
  bad text := '';
begin
  for r in select * from _cleanup_expected order by sch, tbl loop
    execute format('select count(*), coalesce(md5(string_agg(k, %L order by k collate "C")), md5('''')) from (select %s as k from %I.%I) s',
                   ',', r.key_expr, r.sch, r.tbl)
      into actual_n, actual_h;
    if actual_n <> r.n or actual_h <> r.h then
      bad := bad || format('%s.%s expected %s rows, found %s rows%s; ', r.sch, r.tbl, r.n, actual_n, case when actual_n = r.n then ' (same count, DIFFERENT rows)' else '' end);
    end if;
  end loop;
  if bad <> '' then
    raise exception 'ABORT (precondition): the database no longer matches the approved inventory. NOTHING WAS DELETED. Differences: %', bad;
  end if;
end
$pre$;

-- ---------------------------------------------------------
-- 4) DELETE (children first - the order was derived from the 46 real foreign keys and rehearsed). No WHERE is needed: the precondition
--    proved these tables contain exactly the approved rows and nothing else.
-- ---------------------------------------------------------
delete from public.audit_logs;
delete from public.cad_review_comments;
delete from public.cad_review_versions;
delete from public.cad_reviews;
delete from public.calendar_events;
delete from public.comment_mentions;
delete from public.member_applications;
delete from public.migration_exceptions;
delete from public.notifications;
delete from public.purchase_request_items;
delete from public.purchase_status_history;
delete from public.purchase_requests;
delete from public.subsystem_members;
delete from public.task_assignees;
delete from public.task_attachments;
delete from public.task_comments;
delete from public.task_requests;
delete from public.tasks;
delete from public.timeline_milestones;
delete from public.milestones;
delete from public.recurring_events;
delete from public.subsystem_categories;
delete from public.subsystems;
delete from public.timeline_columns;
delete from public.competition_settings;
delete from public.migration_log;

-- ---------------------------------------------------------
-- 5) POST-CHECKS (still inside the transaction; any failure rolls everything back)
-- ---------------------------------------------------------
do $post$
declare
  r record;
  n bigint;
  bad text := '';
begin
  -- 5a) the 26 tables are empty
  for r in select tbl from _cleanup_expected where sch = 'public' and tbl not in ('profiles') loop
    execute format('select count(*) from public.%I', r.tbl) into n;
    if n <> 0 then bad := bad || format('%s still has %s rows; ', r.tbl, n); end if;
  end loop;
  -- 5b) the objects that must stay are unchanged
  if (select count(*) from public.profiles) <> 4 then bad := bad || 'profiles count changed; '; end if;
  if not exists (select 1 from public.profiles where id = 'f15d8647-6a00-493a-8c07-1070f9a66b9b'::uuid and role = 'admin' and approved and active) then bad := bad || 'owner profile is not admin/approved/active; '; end if;
  if (select count(*) from auth.users) <> 4 then bad := bad || 'auth.users count changed; '; end if;
  if (select count(*) from storage.objects) <> 2 then bad := bad || 'storage.objects count changed; '; end if;
  if not exists (select 1 from storage.buckets where id = 'task-attachments' and public = false and file_size_limit = 20971520) then bad := bad || 'task-attachments bucket missing or changed; '; end if;
  if (select count(*) from pg_policies where schemaname = 'storage' and policyname like 'task_attachments_storage_%') <> 2 then bad := bad || 'storage policies changed; '; end if;
  -- 5c) the schema is untouched (same counts as the verified inventory dev_01)
  if (select count(*) from pg_tables where schemaname = 'public') <> 27 then bad := bad || 'public table count <> 27; '; end if;
  if (select count(*) from pg_policies where schemaname in ('public', 'storage')) <> 88 then bad := bad || 'policy count <> 88; '; end if;
  if (select count(*) from pg_trigger t join pg_class c on c.oid = t.tgrelid where not t.tgisinternal and c.relnamespace = 'public'::regnamespace) <> 38 then bad := bad || 'public trigger count <> 38; '; end if;
  if (select count(*) from pg_trigger t join pg_class c on c.oid = t.tgrelid where not t.tgisinternal and t.tgenabled <> 'O' and (c.relnamespace = 'public'::regnamespace or c.oid = 'auth.users'::regclass)) <> 0 then bad := bad || 'a public/auth.users trigger is not enabled; '; end if;
  if (select count(*) from pg_trigger where tgname = 'on_auth_user_created' and tgenabled = 'O') <> 1 then bad := bad || 'on_auth_user_created missing/disabled; '; end if;
  if (select count(*) from pg_proc p where p.pronamespace = 'public'::regnamespace and not exists (select 1 from pg_depend d where d.classid = 'pg_proc'::regclass and d.objid = p.oid and d.deptype = 'e')) <> 36 then bad := bad || 'public function count <> 36; '; end if;
  if bad <> '' then
    raise exception 'ABORT (post-check): % - the transaction is rolled back, nothing was deleted.', bad;
  end if;
end
$post$;

-- ---------------------------------------------------------
-- DRY RUN ends here: undo everything, then report. Nothing above was kept.
-- ---------------------------------------------------------
rollback;
select 'DRY RUN PASSED - guard, precondition, 225 deletes and all post-checks succeeded, then everything was ROLLED BACK. Nothing was changed.' as result,
       (select count(*) from public.tasks) as tasks_still_present_after_rollback;
