import {
  BarChart3,
  Boxes,
  Briefcase,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  ClipboardCheck,
  ClipboardList,
  Flag,
  Gauge,
  GanttChartSquare,
  Handshake,
  LayoutDashboard,
  ListChecks,
  Package,
  PackageCheck,
  Ruler,
  ShoppingCart,
  Truck,
  UsersRound,
  Wallet,
  Warehouse,
  type LucideIcon,
} from 'lucide-react'
import type { NavIconName } from '@/lib/workspaces'

export const NAV_ICONS: Record<NavIconName, LucideIcon> = {
  dashboard: LayoutDashboard,
  tasks: ListChecks,
  calendar: CalendarDays,
  subsystems: Boxes,
  cad: Ruler,
  requests: ClipboardList,
  meetings: ClipboardCheck,
  purchasing: ShoppingCart,
  timeline: GanttChartSquare,
  milestones: Flag,
  sponsorships: Handshake,
  budget: Wallet,
  parts: Package,
  inventory: Warehouse,
  receiving: PackageCheck,
  vendors: Truck,
  reports: BarChart3,
  team: UsersRound,
  deadlines: CalendarClock,
  events: CalendarCheck,
  schedule: UsersRound,
  operations: Gauge,
  business: Briefcase,
}
