-- @@TEMPLATE_GUARD_BEGIN (present ONLY in the template; the generator strips this whole block - banner AND guard - from the generated files)
-- =========================================================
-- !!! THIS FILE IS A TEMPLATE, NOT RUNNABLE SQL. DO NOT PASTE IT INTO THE SQL EDITOR. !!!
-- The runnable files are GENERATED by tools/generate_import_sql.mjs into  supabase/production-prep/results/import/
--     40a_import_DRY_RUN.sql   (run this first)      40b_import_EXECUTE.sql   (only after the dry run, on instruction)
-- If this template is executed by mistake, the first statement below stops it with a clear message and nothing is changed.
-- The generator REMOVES this block, fills every placeholder, and refuses to write a file that still contains one.
-- =========================================================
do $template_guard$
begin
  raise exception 'THIS IS THE TEMPLATE (40_import_TEMPLATE_DO_NOT_RUN.sql), NOT RUNNABLE SQL. Run the GENERATED file instead: supabase/production-prep/results/import/40a_import_DRY_RUN.sql. Nothing was changed.';
end
$template_guard$;
-- @@TEMPLATE_GUARD_END
-- =========================================================
-- __FILE__     bobcat-dev LEGACY DATA IMPORT     __MODE_BANNER__
-- GENERATED by tools/generate_import_sql.mjs from a VALIDATED source export (results/prod_30_source_export.json). This file embeds the legacy data
-- as one jsonb literal, so it contains titles and names - keep it local.
--
-- RUN IT ON: bobcat-dev ONLY (the new live database), in the SQL Editor as postgres.  NEVER on the old legacy project (guard 1 refuses if legacy tables exist).
-- ORDER: run 40a (dry run, ends in ROLLBACK) first; only after you have read its result run 40b (ends in COMMIT); then run 41_post_import_verify_readonly.sql.
-- One transaction: any failed guard, precondition, import statement or post-check leaves NOTHING imported.
--
-- WHAT IT DOES (decisions D3/D4, plan sections 9 and 15):
--   * 7 subsystems (ids preserved verbatim), 25 categories, 15 timeline columns (keys preserved, incl. BREAK/W8), the timeline cells, the recurring event.
--   * TASKS = the union of workspace_state.tasks (winning on overlapping ids) and the relational-only legacy tasks. Rows whose subsystem is unknown
--     (chassis / brakes / rear-suspension) or whose status/priority/title is unusable are NOT guessed: they are held in migration_exceptions with the
--     COMPLETE legacy record, so they can be imported later without losing anything.
--   * ORDERS -> purchase requests + items + one history row each, with the legacy status mapped and the raw status kept in legacy_status_raw
--     (unknown subsystem => held as an exception; both legacy orders are 'chassis').
--   * legacy plaintext lead PINs are NEVER imported (they are stripped at extraction; the payload is checked again here).
--   * attribution: created_by / requested_by / changed_by / updated_by = the importer (the owner's existing profile). The owner's profile row is
--     NEVER written: its fingerprint is compared before and after.
--   * auth.uid()-dependent triggers are DISABLED by name for the duration (they would overwrite created_by/requested_by with NULL, force purchases to
--     Draft, reset completed_at, and fire notifications) and re-enabled before the post-checks, which assert they are enabled and that 0 notifications exist.
--   * migration_log gets one row per legacy record (migrated / exception / skipped); migration_exceptions gets the held records and the unresolved
--     people (assignees, leads, members, requesters). All rows share one batch id.
-- =========================================================
begin;
set local row_security = off;
set local lock_timeout = '15s';

-- ---------------------------------------------------------
-- 0) PAYLOAD (the validated legacy export, embedded as text so its md5 can be checked, then parsed)
-- ---------------------------------------------------------
create temp table _src (t text) on commit drop;
insert into _src values ($legacy$__PAYLOAD__$legacy$);
create temp table _p (j jsonb) on commit drop;
insert into _p select t::jsonb from _src;
create temp table _ctx on commit drop as
  select gen_random_uuid() as batch, '__IMPORTER__'::uuid as importer, now() as imported_at,
         (select md5(to_jsonb(p)::text) from public.profiles p where p.id = '__IMPORTER__'::uuid) as profile_md5;

-- ---------------------------------------------------------
-- 1) GUARDS and PRECONDITIONS: right project, intact payload, importer is the owner, target is the clean post-cleanup database, schema untouched
-- ---------------------------------------------------------
do $guard$
declare
  r record; n bigint; bad text := '';
begin
  if to_regclass('public.workspace_state') is not null or to_regclass('public.orders') is not null or to_regclass('public.subteams') is not null then
    raise exception 'ABORT (guard): legacy tables exist - this looks like the OLD live project. Nothing was changed.';
  end if;
  if to_regclass('public.profiles') is null or to_regclass('public.tasks') is null or to_regclass('public.migration_log') is null then
    raise exception 'ABORT (guard): the v2 tables are missing - this is not bobcat-dev. Nothing was changed.';
  end if;
  if md5((select t from _src)) <> '__PAYLOAD_MD5__' then
    raise exception 'ABORT (payload): the embedded legacy data does not match the md5 recorded at generation (corrupted paste?). Nothing was changed.';
  end if;
  if (select t from _src) ~* 'leadpin' then
    raise exception 'ABORT (payload): the payload contains "leadPin" - lead PINs must never be imported. Nothing was changed.';
  end if;
  if not exists (select 1 from public.profiles where id = '__IMPORTER__'::uuid and role in ('cto', 'admin') and approved and active)
     or not exists (select 1 from auth.users where id = '__IMPORTER__'::uuid) then
    raise exception 'ABORT (importer): the importer profile is not an approved, active cto/admin. Nothing was changed.';
  end if;
  if (select count(*) from public.profiles) <> 1 or (select count(*) from auth.users) <> 1 then
    bad := bad || 'the database is not the clean post-cleanup state (expected exactly 1 profile and 1 auth user); ';
  end if;
  for r in select tablename t from pg_tables where schemaname = 'public' and tablename <> 'profiles' loop
    execute format('select count(*) from public.%I', r.t) into n;
    if n <> 0 then bad := bad || format('%s already has %s rows; ', r.t, n); end if;
  end loop;
  if (select count(*) from pg_tables where schemaname = 'public') <> 27 then bad := bad || 'public table count <> 27; '; end if;
  if (select count(*) from pg_policies where schemaname in ('public', 'storage')) <> 88 then bad := bad || 'policy count <> 88; '; end if;
  if (select count(*) from pg_trigger t join pg_class c on c.oid = t.tgrelid where not t.tgisinternal and c.relnamespace = 'public'::regnamespace) <> 38 then bad := bad || 'public trigger count <> 38; '; end if;
  if (select count(*) from pg_trigger t join pg_class c on c.oid = t.tgrelid where not t.tgisinternal and t.tgenabled <> 'O' and (c.relnamespace = 'public'::regnamespace or c.oid = 'auth.users'::regclass)) <> 0 then bad := bad || 'a trigger is already not enabled; '; end if;
  if (select count(*) from pg_proc p where p.pronamespace = 'public'::regnamespace and not exists (select 1 from pg_depend d where d.classid = 'pg_proc'::regclass and d.objid = p.oid and d.deptype = 'e')) <> __FUNCS__ then bad := bad || 'public function count <> __FUNCS__; '; end if;
  if bad <> '' then
    raise exception 'ABORT (precondition): the target is not the expected clean bobcat-dev. NOTHING WAS IMPORTED. Problems: %', bad;
  end if;
end
$guard$;

-- ---------------------------------------------------------
-- 2) DISABLE the auth.uid()-dependent / notification triggers BY NAME (re-enabled in step 12; the post-checks assert they are enabled again)
-- ---------------------------------------------------------
alter table public.tasks disable trigger tasks_before_write;                                  -- overwrites created_by, primary_owner_id, completed_at
alter table public.timeline_milestones disable trigger timeline_milestones_before_write;      -- overwrites updated_by
alter table public.purchase_requests disable trigger purchase_requests_before_write;          -- forces Draft / requested_by = auth.uid()
alter table public.purchase_requests disable trigger purchase_requests_log_status_change;     -- history row with changed_by = auth.uid() (NULL)
alter table public.purchase_requests disable trigger purchase_requests_notify_status_change;
alter table public.task_assignees disable trigger task_assignees_notify_assignment;
alter table public.task_requests disable trigger task_requests_notify_reviewed;
alter table public.cad_reviews disable trigger cad_reviews_notify_status_change;
alter table public.comment_mentions disable trigger comment_mentions_notify;
alter table public.member_applications disable trigger member_applications_notify_reviewed;

create function pg_temp.try_date(txt text) returns date language plpgsql immutable as $f$
begin
  if txt is null or txt !~ '^\d{4}-\d{2}-\d{2}$' then return null; end if;
  return txt::date;
exception when others then
  return null;
end
$f$;
create temp table _ex (entity_type text, raw_value text, context jsonb) on commit drop;   -- exceptions collected, inserted at the end

-- ---------------------------------------------------------
-- 3) SUBSYSTEMS (7) - ids preserved verbatim - and CATEGORIES (25)
-- ---------------------------------------------------------
create temp table _tax on commit drop as
  select e, ord from _p, jsonb_array_elements(_p.j -> 'workspace_state' -> 'taxonomy') with ordinality as t(e, ord);

insert into public.subsystems (id, name, active)
select e ->> 'id', e ->> 'name', true from _tax order by ord;

create temp table _cat_map (subsystem_id text, name text, id uuid, primary key (subsystem_id, name)) on commit drop;
with ins as (
  insert into public.subsystem_categories (subsystem_id, name, engineering_rule, active)
  select s.e ->> 'id', c.e ->> 'name', nullif(c.e ->> 'rule', ''), true
  from _tax s, jsonb_array_elements(coalesce(s.e -> 'categories', '[]'::jsonb)) with ordinality as c(e, co)
  order by s.ord, c.co
  returning id, subsystem_id, name)
insert into _cat_map select subsystem_id, name, id from ins;

create temp table _alias (legacy text primary key, target text) on commit drop;       -- explicit owner-approved subsystem aliases (empty in the initial import)
insert into _alias select k, v #>> '{}' from _p, jsonb_each(coalesce(_p.j -> 'subsystem_aliases', '{}'::jsonb)) as a(k, v);

-- ---------------------------------------------------------
-- 4) TIMELINE: 15 columns (keys preserved verbatim), the cells, the recurring event
-- ---------------------------------------------------------
create temp table _cols on commit drop as
  select e, ord from _p, jsonb_array_elements(_p.j -> 'workspace_state' -> 'timeline_columns') with ordinality as t(e, ord);
insert into public.timeline_columns (key, label, highlight, sort_order, active)
select e ->> 'key', coalesce(nullif(e ->> 'label', ''), e ->> 'key'),
       case when jsonb_typeof(e -> 'highlight') = 'boolean' then (e ->> 'highlight')::boolean
            else lower(coalesce(nullif(trim(e ->> 'highlight'), ''), 'none')) not in ('none', 'false', 'no', '0', 'off') end,   -- 'none' -> false, 'emerald' -> true
       ord::int, true
from _cols order by ord;

create temp table _cells on commit drop as
  select sub.key as subsystem_id, cell.key as col, nullif(trim(cell.value #>> '{}'), '') as txt
  from _p,
       jsonb_each(case when jsonb_typeof(_p.j -> 'workspace_state' -> 'timeline_milestones') = 'object' then _p.j -> 'workspace_state' -> 'timeline_milestones' else '{}'::jsonb end) as sub,
       jsonb_each(case when jsonb_typeof(sub.value) = 'object' then sub.value else '{}'::jsonb end) as cell;
alter table _cells add column ok boolean;
update _cells set ok = txt is not null and exists (select 1 from public.subsystems s where s.id = _cells.subsystem_id) and exists (select 1 from public.timeline_columns k where k.key = _cells.col);
insert into public.timeline_milestones (subsystem_id, timeline_column_key, milestone_text, updated_by)
select subsystem_id, col, txt, (select importer from _ctx) from _cells where ok;
insert into _ex select 'timeline_cell_orphan', format('timeline cell %s / %s', subsystem_id, col), jsonb_build_object('subsystem_id', subsystem_id, 'column', col, 'text', txt) from _cells where txt is not null and not ok;

create temp table _rec on commit drop as
  select e, ord, gen_random_uuid() as new_id,
         (e ->> 'id') as legacy_id,
         (nullif(trim(e ->> 'title'), '') is not null and (e ->> 'dayOfWeek') ~ '^[0-6]$') as ok
  from _p, jsonb_array_elements(_p.j -> 'workspace_state' -> 'recurring_events') with ordinality as t(e, ord);
insert into public.recurring_events (id, title, day_of_week, time_label, color, subsystem_id, active)
select new_id, e ->> 'title', (e ->> 'dayOfWeek')::smallint, nullif(e ->> 'time', ''), nullif(e ->> 'color', ''), null, true from _rec where ok order by ord;
insert into _ex select 'recurring_event_invalid', format('recurring event %s', legacy_id), jsonb_build_object('record', e) from _rec where not ok;

-- ---------------------------------------------------------
-- 5) TASKS = union of workspace_state.tasks (WINS on overlapping ids) and the relational-only legacy tasks
-- ---------------------------------------------------------
create temp table _t on commit drop as
with ws as (select e as r, ord from _p, jsonb_array_elements(_p.j -> 'workspace_state' -> 'tasks') with ordinality as t(e, ord)),
     rel as (select e as r, ord from _p, jsonb_array_elements(_p.j -> 'tasks') with ordinality as t(e, ord)),
     ws_ids as (select r ->> 'id' as id from ws),
     u as (
       select 'workspace_state'::text as source, ws.r ->> 'id' as legacy_id, ws.r as raw, ws.ord,
              ws.r ->> 'title' as title, ws.r ->> 'notes' as notes, ws.r ->> 'subsystemId' as sub, ws.r ->> 'category' as cat,
              ws.r ->> 'priority' as prio, ws.r ->> 'status' as stat, ws.r ->> 'assignee' as assignee, ws.r ->> 'deadline' as deadline_txt,
              (select rr.r ->> 'created_at' from rel rr where rr.r ->> 'id' = ws.r ->> 'id') as rel_created_at
       from ws
       union all
       select 'relational', rel.r ->> 'id', rel.r, rel.ord, rel.r ->> 'title', rel.r ->> 'notes', rel.r ->> 'subsystem_id', rel.r ->> 'category',
              rel.r ->> 'priority', rel.r ->> 'status', rel.r ->> 'assignee', rel.r ->> 'deadline', rel.r ->> 'created_at'
       from rel where rel.r ->> 'id' not in (select id from ws_ids))
select u.*, gen_random_uuid() as new_id from u;
alter table _t add column eff_sub text, add column hold text, add column cat_id uuid, add column deadline_ts timestamptz, add column deadline_bad boolean, add column cat_bad boolean;

update _t set eff_sub = case when exists (select 1 from public.subsystems s where s.id = _t.sub) then _t.sub
                             else (select a.target from _alias a where a.legacy = _t.sub and exists (select 1 from public.subsystems s where s.id = a.target)) end;
update _t set hold = case
    when nullif(trim(title), '') is null then 'task_invalid_title'
    when eff_sub is null then 'task_unmapped_subsystem'                                                        -- D4: never guessed
    when stat is null or stat not in ('To Do', 'In Progress', 'Blocked', 'Review', 'Complete') then 'task_invalid_status'
    when prio is null or prio not in ('Critical', 'High', 'Medium', 'Low') then 'task_invalid_priority'
  end;
update _t set cat_id = (select m.id from _cat_map m where m.subsystem_id = _t.eff_sub and m.name = _t.cat),
              deadline_ts = case when pg_temp.try_date(deadline_txt) is not null then (pg_temp.try_date(deadline_txt)::timestamp) at time zone 'UTC' end;   -- date -> midnight UTC, the app's own convention
update _t set cat_bad = (nullif(trim(cat), '') is not null and cat_id is null),
              deadline_bad = (nullif(trim(deadline_txt), '') is not null and deadline_ts is null);

insert into public.tasks (id, title, description, subsystem_id, category_id, priority, status, deadline, created_by, completed_at, created_at, legacy_id, legacy_assignee_raw)
select t.new_id, t.title, nullif(trim(t.notes), ''), t.eff_sub, t.cat_id, t.prio::public.task_priority, t.stat::public.task_status, t.deadline_ts,
       c.importer, case when t.stat = 'Complete' then c.imported_at end, coalesce(t.rel_created_at::timestamptz, c.imported_at), t.legacy_id, nullif(trim(t.assignee), '')
from _t t, _ctx c where t.hold is null order by (t.source = 'workspace_state') desc, t.ord;

insert into _ex select hold, format('task %s · %s · %s', legacy_id, case hold when 'task_unmapped_subsystem' then 'legacy subsystem "' || coalesce(sub, '') || '"' else replace(hold, 'task_', '') end, left(coalesce(title, ''), 80)),
       jsonb_build_object('source', source, 'legacy_id', legacy_id, 'unmapped_field', case hold when 'task_unmapped_subsystem' then 'subsystem_id' end,
                          'unmapped_value', case hold when 'task_unmapped_subsystem' then sub end, 'record', raw, 'relational_created_at', rel_created_at)
from _t where hold is not null;
insert into _ex select 'task_invalid_category', format('task %s · category "%s" is not in subsystem %s', legacy_id, cat, eff_sub),
       jsonb_build_object('legacy_id', legacy_id, 'subsystem_id', eff_sub, 'category', cat, 'note', 'imported with category_id NULL') from _t where hold is null and cat_bad;
insert into _ex select 'task_invalid_deadline', format('task %s · deadline "%s" is not an ISO date', legacy_id, deadline_txt),
       jsonb_build_object('legacy_id', legacy_id, 'deadline', deadline_txt, 'note', 'imported with deadline NULL') from _t where hold is null and deadline_bad;
insert into _ex select 'task_assignee', trim(assignee), jsonb_build_object('legacy_task_ids', jsonb_agg(legacy_id order by legacy_id), 'task_count', count(*), 'note', 'legacy_assignee_raw preserved; assign in the app after sign-up')
from _t where hold is null and nullif(trim(assignee), '') is not null group by trim(assignee);

-- ---------------------------------------------------------
-- 6) ORDERS -> purchase requests + items + history (status mapped, raw status kept in legacy_status_raw)
-- ---------------------------------------------------------
create temp table _pmap (legacy text primary key, mapped public.purchase_status) on commit drop;
insert into _pmap values ('draft', 'Draft'), ('requested', 'Submitted'), ('submitted', 'Submitted'), ('under review', 'Under Review'), ('approved', 'Approved'), ('ordered', 'Ordered'),
  ('shipped', 'In Transit'), ('in transit', 'In Transit'), ('arrived in shop', 'Arrived in Shop'), ('arrived', 'Arrived in Shop'), ('received', 'Arrived in Shop'), ('delivered', 'Arrived in Shop'),
  ('complete', 'Completed'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('denied', 'Rejected'), ('cancelled', 'Cancelled'), ('canceled', 'Cancelled');
create temp table _o on commit drop as
  select e as r, ord, e ->> 'id' as legacy_id, e ->> 'item' as item, e ->> 'subsystem_id' as sub, e ->> 'status' as stat_raw, e ->> 'requested_by' as requester, e ->> 'urgency' as urgency,
         e ->> 'vendor' as vendor, e ->> 'vendor_url' as vendor_url, e ->> 'part_number' as part_number, (e ->> 'qty')::int as qty, (e ->> 'unit_price')::numeric as unit_price,
         (e ->> 'submitted_at')::timestamptz as submitted_at, gen_random_uuid() as req_id, gen_random_uuid() as item_id, gen_random_uuid() as hist_id
  from _p, jsonb_array_elements(_p.j -> 'orders') with ordinality as t(e, ord);
alter table _o add column eff_sub text, add column hold text, add column mapped public.purchase_status, add column status_unmapped boolean;
update _o set eff_sub = case when exists (select 1 from public.subsystems s where s.id = _o.sub) then _o.sub
                             else (select a.target from _alias a where a.legacy = _o.sub and exists (select 1 from public.subsystems s where s.id = a.target)) end;
update _o set mapped = coalesce((select m.mapped from _pmap m where m.legacy = lower(trim(_o.stat_raw))), 'Draft'),
              status_unmapped = not exists (select 1 from _pmap m where m.legacy = lower(trim(_o.stat_raw)));
update _o set hold = case when nullif(trim(item), '') is null then 'purchase_request_invalid_title'
                          when eff_sub is null then 'purchase_request_unmapped_subsystem'                      -- D4: both legacy orders are 'chassis' => held, never guessed
                          when qty is null or qty <= 0 then 'purchase_request_invalid_quantity' end;
insert into public.purchase_requests (id, subsystem_id, requested_by, title, description, vendor, status, reviewed_by, reviewed_at, created_at, legacy_id, legacy_status_raw)
select o.req_id, o.eff_sub, c.importer, o.item,
       nullif(trim(concat_ws(E'\n', case when nullif(trim(o.urgency), '') is not null then 'Urgency: ' || trim(o.urgency) end, case when nullif(trim(o.requester), '') is not null then 'Legacy requester: ' || trim(o.requester) end)), ''),
       nullif(trim(o.vendor), ''), o.mapped, null, null, coalesce(o.submitted_at, c.imported_at), o.legacy_id, o.stat_raw
from _o o, _ctx c where o.hold is null order by o.ord;
insert into public.purchase_request_items (id, purchase_request_id, description, quantity, unit_cost, link, notes, legacy_id)
select o.item_id, o.req_id, o.item, o.qty, case when o.unit_price >= 0 then o.unit_price end, nullif(trim(o.vendor_url), ''),
       case when nullif(trim(o.part_number), '') is not null then 'Part #: ' || trim(o.part_number) end, o.legacy_id
from _o o where o.hold is null;
insert into public.purchase_status_history (id, purchase_request_id, from_status, to_status, changed_by, changed_at, note, legacy_id)
select o.hist_id, o.req_id, null, o.mapped, c.importer, coalesce(o.submitted_at, c.imported_at), 'Imported from legacy orders; legacy status: ' || coalesce(o.stat_raw, '(none)'), o.legacy_id
from _o o, _ctx c where o.hold is null;
insert into _ex select hold, format('order %s · %s · %s', legacy_id, case hold when 'purchase_request_unmapped_subsystem' then 'legacy subsystem "' || coalesce(sub, '') || '"' else replace(hold, 'purchase_request_', '') end, left(coalesce(item, ''), 80)),
       jsonb_build_object('source', 'public.orders', 'legacy_id', legacy_id, 'unmapped_field', case hold when 'purchase_request_unmapped_subsystem' then 'subsystem_id' end,
                          'unmapped_value', case hold when 'purchase_request_unmapped_subsystem' then sub end, 'record', r) from _o where hold is not null;
insert into _ex select 'purchase_status', format('order %s · legacy status "%s" is not a known status (imported as Draft)', legacy_id, stat_raw), jsonb_build_object('legacy_id', legacy_id, 'legacy_status', stat_raw)
from _o where hold is null and status_unmapped;
insert into _ex select 'purchase_requester', trim(requester), jsonb_build_object('legacy_order_ids', jsonb_agg(legacy_id order by legacy_id), 'note', 'raw requester preserved in the purchase description')
from _o where hold is null and nullif(trim(requester), '') is not null group by trim(requester);

-- ---------------------------------------------------------
-- 7) PEOPLE that have no account yet -> unresolved exceptions (resolved later by the CTO/admin). NEVER a PIN.
-- ---------------------------------------------------------
insert into _ex select 'subsystem_lead', trim(e ->> 'lead'), jsonb_build_object('subsystem_id', e ->> 'id', 'source', 'workspace_state.taxonomy') from _tax where nullif(trim(e ->> 'lead'), '') is not null;
insert into _ex select 'subsystem_member', trim(m #>> '{}'), jsonb_build_object('subsystem_id', s.e ->> 'id', 'source', 'workspace_state.taxonomy')
from _tax s, jsonb_array_elements(coalesce(s.e -> 'members', '[]'::jsonb)) as m where nullif(trim(m #>> '{}'), '') is not null;
create temp table _st on commit drop as select e, ord from _p, jsonb_array_elements(_p.j -> 'subteams') with ordinality as t(e, ord);
insert into _ex select 'subteam_unmapped_subsystem', format('subteam %s · legacy subsystem "%s"', e ->> 'id', coalesce(e ->> 'subsystem_id', '')),
       jsonb_build_object('source', 'public.subteams', 'legacy_id', e ->> 'id', 'unmapped_field', 'subsystem_id', 'unmapped_value', e ->> 'subsystem_id', 'record', e)
from _st where not exists (select 1 from public.subsystems s where s.id = e ->> 'subsystem_id')
           and not exists (select 1 from _alias a where a.legacy = e ->> 'subsystem_id' and exists (select 1 from public.subsystems s where s.id = a.target));
insert into _ex select 'subsystem_lead', trim(e ->> 'lead'), jsonb_build_object('subteam_id', e ->> 'id', 'subsystem_id', e ->> 'subsystem_id', 'source', 'public.subteams') from _st where nullif(trim(e ->> 'lead'), '') is not null;
insert into _ex select 'subsystem_member', trim(m #>> '{}'), jsonb_build_object('subteam_id', s.e ->> 'id', 'subsystem_id', s.e ->> 'subsystem_id', 'source', 'public.subteams')
from _st s, jsonb_array_elements(coalesce(s.e -> 'members', '[]'::jsonb)) as m where nullif(trim(m #>> '{}'), '') is not null;

-- ---------------------------------------------------------
-- 8) EXCEPTIONS and MIGRATION LOG (one shared batch id; every legacy record is accounted for)
-- ---------------------------------------------------------
insert into public.migration_exceptions (migration_batch_id, entity_type, raw_value, context)
select (select batch from _ctx), entity_type, raw_value, context from _ex order by entity_type, raw_value;

insert into public.migration_log (migration_batch_id, entity_type, legacy_id_or_key, new_id, match_method, status, notes)
select (select batch from _ctx), 'workspace_state', p.j -> 'workspace_state' ->> 'id', null, 'document', 'migrated',
       'exported_at=' || (p.j -> 'export_meta' ->> 'exported_at') || '; payload_md5=__PAYLOAD_MD5__; ws_updated_at=' || (p.j -> 'workspace_state' ->> 'updated_at') from _p p;
insert into public.migration_log (migration_batch_id, entity_type, legacy_id_or_key, new_id, match_method, status, notes)
select (select batch from _ctx), 'subsystem', e ->> 'id', null, 'id_preserved', 'migrated', 'text id preserved verbatim; lead PIN not migrated' from _tax;
insert into public.migration_log (migration_batch_id, entity_type, legacy_id_or_key, new_id, match_method, status, notes)
select (select batch from _ctx), 'subsystem_category', subsystem_id || '::' || name, id, 'subsystem_id+name', 'migrated', null from _cat_map;
insert into public.migration_log (migration_batch_id, entity_type, legacy_id_or_key, new_id, match_method, status, notes)
select (select batch from _ctx), 'timeline_column', e ->> 'key', null, 'key_preserved', 'migrated',
       'label=' || coalesce(e ->> 'label', '') || '; raw highlight=' || coalesce(e ->> 'highlight', '') from _cols;
insert into public.migration_log (migration_batch_id, entity_type, legacy_id_or_key, new_id, match_method, status, notes)
select (select batch from _ctx), 'timeline_cell', subsystem_id || '/' || col, null, 'composite_key', (case when ok then 'migrated' when txt is null then 'skipped' else 'exception' end)::public.migration_log_status,
       case when txt is null then 'blank cell' when not ok then 'orphan cell (unknown subsystem or column)' end from _cells;
insert into public.migration_log (migration_batch_id, entity_type, legacy_id_or_key, new_id, match_method, status, notes)
select (select batch from _ctx), 'recurring_event', coalesce(legacy_id, 'ord-' || ord), case when ok then new_id end, 'new_uuid', (case when ok then 'migrated' else 'exception' end)::public.migration_log_status, null from _rec;
insert into public.migration_log (migration_batch_id, entity_type, legacy_id_or_key, new_id, match_method, status, notes)
select (select batch from _ctx), 'task', legacy_id, case when hold is null then new_id end, case source when 'workspace_state' then case when rel_created_at is not null then 'workspace_state_wins_over_relational' else 'workspace_state' end else 'relational_only' end,
       (case when hold is null then 'migrated' else 'exception' end)::public.migration_log_status, hold from _t;
insert into public.migration_log (migration_batch_id, entity_type, legacy_id_or_key, new_id, match_method, status, notes)
select (select batch from _ctx), 'task_relational_superseded', r ->> 'id', null, 'superseded_by_workspace_state', 'skipped', 'same id exists in workspace_state.tasks, which wins (D3)'
from _p, jsonb_array_elements(_p.j -> 'tasks') as r where exists (select 1 from _t x where x.legacy_id = r ->> 'id' and x.source = 'workspace_state');
insert into public.migration_log (migration_batch_id, entity_type, legacy_id_or_key, new_id, match_method, status, notes)
select (select batch from _ctx), 'order', legacy_id, case when hold is null then req_id end, 'orders_row', (case when hold is null then 'migrated' else 'exception' end)::public.migration_log_status, coalesce(hold, 'legacy status: ' || coalesce(stat_raw, '')) from _o;
insert into public.migration_log (migration_batch_id, entity_type, legacy_id_or_key, new_id, match_method, status, notes)
select (select batch from _ctx), 'subteam', e ->> 'id', null, 'no_target_table', 'skipped', 'v2 has no team concept; lead/members recorded as exceptions' from _st;

-- ---------------------------------------------------------
-- 9) RE-ENABLE every trigger disabled in step 2
-- ---------------------------------------------------------
alter table public.tasks enable trigger tasks_before_write;
alter table public.timeline_milestones enable trigger timeline_milestones_before_write;
alter table public.purchase_requests enable trigger purchase_requests_before_write;
alter table public.purchase_requests enable trigger purchase_requests_log_status_change;
alter table public.purchase_requests enable trigger purchase_requests_notify_status_change;
alter table public.task_assignees enable trigger task_assignees_notify_assignment;
alter table public.task_requests enable trigger task_requests_notify_reviewed;
alter table public.cad_reviews enable trigger cad_reviews_notify_status_change;
alter table public.comment_mentions enable trigger comment_mentions_notify;
alter table public.member_applications enable trigger member_applications_notify_reviewed;

-- ---------------------------------------------------------
-- 10) POST-CHECKS: the result must equal the independently computed expectation and every invariant must hold (any failure rolls everything back)
-- ---------------------------------------------------------
do $post$
declare
  exp jsonb := $exp$__EXPECT__$exp$::jsonb;
  act jsonb; k text; bad text := ''; c record;
begin
  select * into c from _ctx;
  act := jsonb_build_object(
    'subsystems', (select count(*) from public.subsystems),
    'categories', (select count(*) from public.subsystem_categories),
    'timeline_columns', (select count(*) from public.timeline_columns),
    'timeline_columns_highlighted', (select count(*) from public.timeline_columns where highlight),
    'timeline_milestones', (select count(*) from public.timeline_milestones),
    'recurring_events', (select count(*) from public.recurring_events),
    'tasks', (select count(*) from public.tasks),
    'tasks_complete', (select count(*) from public.tasks where status = 'Complete'),
    'tasks_with_deadline', (select count(*) from public.tasks where deadline is not null),
    'tasks_with_category', (select count(*) from public.tasks where category_id is not null),
    'tasks_with_assignee_raw', (select count(*) from public.tasks where legacy_assignee_raw is not null),
    'purchase_requests', (select count(*) from public.purchase_requests),
    'purchase_items', (select count(*) from public.purchase_request_items),
    'purchase_history', (select count(*) from public.purchase_status_history),
    'exceptions_by_type', (select coalesce(jsonb_object_agg(entity_type, n), '{}'::jsonb) from (select entity_type, count(*) as n from public.migration_exceptions group by 1) x),
    'log_by_entity_status', (select coalesce(jsonb_object_agg(entity_type || ':' || status, n), '{}'::jsonb) from (select entity_type, status, count(*) as n from public.migration_log group by 1, 2) x)
  );
  for k in select jsonb_object_keys(exp) loop
    if act -> k is distinct from exp -> k then bad := bad || format('%s: expected %s but found %s; ', k, exp -> k, act -> k); end if;
  end loop;
  -- invariants
  if (select count(*) from public.notifications) <> 0 then bad := bad || 'NOTIFICATIONS WERE CREATED (import must be silent); '; end if;
  if (select count(*) from public.audit_logs) + (select count(*) from public.task_assignees) + (select count(*) from public.task_comments) + (select count(*) from public.cad_reviews)
     + (select count(*) from public.calendar_events) + (select count(*) from public.milestones) + (select count(*) from public.competition_settings) + (select count(*) from public.member_applications) <> 0 then bad := bad || 'rows appeared in a table the import must not touch; '; end if;
  if (select count(*) from public.tasks where created_by <> c.importer or legacy_id is null or primary_owner_id is not null) <> 0 then bad := bad || 'task attribution/legacy_id/owner wrong; '; end if;
  if (select count(*) from public.timeline_milestones where updated_by <> c.importer) + (select count(*) from public.purchase_requests where requested_by <> c.importer)
     + (select count(*) from public.purchase_status_history where changed_by <> c.importer) <> 0 then bad := bad || 'attribution to the importer is wrong; '; end if;
  if (select count(*) from public.tasks t where t.category_id is not null and not exists (select 1 from public.subsystem_categories sc where sc.id = t.category_id and sc.subsystem_id = t.subsystem_id)) <> 0 then bad := bad || 'a task category does not belong to its subsystem; '; end if;
  if (select count(*) from public.migration_log l where l.entity_type = 'task' and l.status = 'migrated' and not exists (select 1 from public.tasks t where t.id = l.new_id and t.legacy_id = l.legacy_id_or_key)) <> 0 then bad := bad || 'migration_log task rows do not match tasks; '; end if;
  if (select count(*) from public.migration_exceptions where migration_batch_id <> c.batch or resolution_status <> 'unresolved') + (select count(*) from public.migration_log where migration_batch_id <> c.batch) <> 0 then bad := bad || 'batch id / resolution status wrong; '; end if;
  if (select count(*) from public.migration_exceptions where context::text ~* 'leadpin' or raw_value ~* 'leadpin') <> 0 then bad := bad || 'A LEAD PIN REFERENCE IS PRESENT; '; end if;
  -- the owner's profile and the auth user are exactly as before
  if (select count(*) from public.profiles) <> 1 or (select count(*) from auth.users) <> 1 then bad := bad || 'profiles/auth.users count changed; '; end if;
  if (select md5(to_jsonb(p)::text) from public.profiles p where p.id = c.importer) is distinct from c.profile_md5 then bad := bad || 'THE OWNER PROFILE ROW CHANGED; '; end if;
  -- triggers back to normal, schema untouched
  if (select count(*) from pg_trigger t join pg_class cl on cl.oid = t.tgrelid where not t.tgisinternal and t.tgenabled <> 'O' and (cl.relnamespace = 'public'::regnamespace or cl.oid = 'auth.users'::regclass)) <> 0 then bad := bad || 'a trigger is left disabled; '; end if;
  if (select count(*) from pg_trigger t join pg_class cl on cl.oid = t.tgrelid where not t.tgisinternal and cl.relnamespace = 'public'::regnamespace) <> 38 then bad := bad || 'public trigger count <> 38; '; end if;
  if (select count(*) from pg_tables where schemaname = 'public') <> 27 or (select count(*) from pg_policies where schemaname in ('public', 'storage')) <> 88 then bad := bad || 'table/policy count changed; '; end if;
  if (select count(*) from pg_proc p where p.pronamespace = 'public'::regnamespace and not exists (select 1 from pg_depend d where d.classid = 'pg_proc'::regclass and d.objid = p.oid and d.deptype = 'e')) <> __FUNCS__ then bad := bad || 'function count changed; '; end if;
  if bad <> '' then
    raise exception 'ABORT (post-check): % - the transaction is rolled back, NOTHING WAS IMPORTED.', bad;
  end if;
end
$post$;

-- @@MODE_END@@ (replaced by the generator with ROLLBACK + report for the dry run, or COMMIT + report for the execute script)
